name: CI

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main
      - feature/*

jobs:
  tests:
    name: Flow CLI Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
          submodules: recursive
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.23.x"
      - uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Cache Flow Emulator Fork Data
        uses: actions/cache@v4
        with:
          path: .flow-fork-cache
          key: ${{ runner.os }}-flow-emulator-fork-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-flow-emulator-fork-
      - name: Install Flow CLI
        run: sh -ci "$(curl -fsSL https://raw.githubusercontent.com/onflow/flow-cli/master/install.sh)" -- v2.16.0
      - name: Update PATH and show Flow version
        run: |
          echo "/root/.local/bin" >> $GITHUB_PATH
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          which flow || true
          flow version
      - name: Install dependencies
        run: flow deps install --skip-alias --skip-deployments
      - name: Run tests
        run: make ci
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
